---
fail_fast: true

repos:
# Generic repos
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.0
  hooks:
    - id: check-yaml
      args: [--allow-multiple-documents]
    - id: end-of-file-fixer
    - id: trailing-whitespace
    # This prevents issues if not managing git-lfs
    - id: check-added-large-files
    # This prevents problems for multi OS
    - id: check-case-conflict
    # This prevents having executables that cannot be executed
    - id: check-executables-have-shebangs
    # Check JSON, XML and YAML
    - id: check-json
    # Prevents commiting unmergeable files
    - id: check-merge-conflict
    # Removes spaces at end of lines
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    # AWS Creds
    - id: detect-aws-credentials
      args: [--allow-missing-credentials]
    # Prevents commiting to master
    # - id: no-commit-to-branch

# Change tabs for spaces
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.9
  hooks:
    - id: remove-tabs
      args: [--whitespaces-count, "2"]
